### ISSUE TITLE
I Got "Worker error: too many indices for array: array is 2-dimensional, but 3 were indexed" when using image-inpait-outpaint

### ISSUE THREAD

**Issue by mrhan1993** [mrhan1993/Fooocus-API#58]
![with_points](https://github.com/konieshadow/Fooocus-API/assets/50648276/af7f09cb-682e-4db5-a3fb-848a8e087cec)
![mask_0](https://github.com/konieshadow/Fooocus-API/assets/50648276/b75b7353-8b17-4ae6-a205-eb61b2f4161f)

I try use this 2 pic as input image and mask in Swagger page, and all other params are default, but got "Worker error: too many indices for array: array is 2-dimensional, but 3 were indexed" in command line, How should I use this interface or did I get the parameters wrong?

**Comment by mrhan1993** [comment]
```
curl -X 'POST' \
  'http://192.168.5.222:8888/v1/generation/image-inpait-outpaint' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'sharpness=2' \
  -F 'input_mask=@mask_0.png;type=image/png' \
  -F 'advanced_params=' \
  -F 'guidance_scale=4' \
  -F 'prompt=' \
  -F 'l1=sd_xl_offset_example-lora_1.0.safetensors' \
  -F 'input_image=@with_points.png;type=image/png' \
  -F 'l2=' \
  -F 'l3=' \
  -F 'l4=' \
  -F 'l5=' \
  -F 'require_base64=false' \
  -F 'async_process=false' \
  -F 'image_number=1' \
  -F 'negative_prompt=' \
  -F 'refiner_switch=0.5' \
  -F 'base_model_name=juggernautXL_version6Rundiffusion.safetensors' \
  -F 'image_seed=-1' \
  -F 'style_selections=Fooocus V2,Fooocus Enhance,Fooocus Sharp' \
  -F 'outpaint_selections=' \
  -F 'w1=0.1' \
  -F 'w2=0.1' \
  -F 'refiner_model_name=None' \
  -F 'aspect_ratios_selection=1152×896' \
  -F 'w3=0.1' \
  -F 'performance_selection=Speed' \
  -F 'w4=0.1' \
  -F 'w5=0.1'
```
here is the post data

**Comment by konieshadow** [comment]
@mrhan1993 Just fixed at v0.3.15. Thanks for feedback.

**Comment by mrhan1993** [comment]
> @mrhan1993 Just fixed at v0.3.15. Thanks for feedback.

is worked, thx for your work.

**Comment by CyrusVorwald** [comment]
This update isn't reflected in the replicate model, so the error still occurs there.

**Comment by konieshadow** [comment]
@CyrusVorwald Just updated the replicate model.

**Comment by mrhan1993** [comment]
@konieshadow send a mail to your hotmail, have a look?
